// Seed data — 12 students with varied risk profiles for development/demo
export const SEED_STUDENTS = [
    {
        id: 'seed-001',
        name: 'Marcus Thompson',
        studentId: 'ST-2024-001',
        grade: '10',
        subject: 'English',
        attendanceRate: 58,
        gpa: 1.4,
        assignmentCompletion: 42,
        behaviorReferrals: 4,
        lateSubmissions: 12,
        notes: 'Significant drop since October. Parents contacted, no response.',
        tags: ['At-Risk', 'ELL'],
        lastRiskScore: 87,
        lastRiskCategory: 'Critical',
    },
    {
        id: 'seed-002',
        name: 'Priya Sharma',
        studentId: 'ST-2024-002',
        grade: '11',
        subject: 'Mathematics',
        attendanceRate: 94,
        gpa: 3.8,
        assignmentCompletion: 97,
        behaviorReferrals: 0,
        lateSubmissions: 1,
        notes: 'Consistent high performer.',
        tags: [],
        lastRiskScore: 8,
        lastRiskCategory: 'Low',
    },
    {
        id: 'seed-003',
        name: 'Jerome Williams',
        studentId: 'ST-2024-003',
        grade: '9',
        subject: 'Science',
        attendanceRate: 72,
        gpa: 2.1,
        assignmentCompletion: 61,
        behaviorReferrals: 2,
        lateSubmissions: 7,
        notes: 'Attendance declining since January. Seems distracted.',
        tags: ['Monitored'],
        lastRiskScore: 63,
        lastRiskCategory: 'At Risk',
    },
    {
        id: 'seed-004',
        name: 'Sofia Mendez',
        studentId: 'ST-2024-004',
        grade: '12',
        subject: 'History',
        attendanceRate: 88,
        gpa: 3.2,
        assignmentCompletion: 82,
        behaviorReferrals: 0,
        lateSubmissions: 3,
        notes: 'Strong student, occasional late work.',
        tags: [],
        lastRiskScore: 22,
        lastRiskCategory: 'Low',
    },
    {
        id: 'seed-005',
        name: 'Damien Lee',
        studentId: 'ST-2024-005',
        grade: '10',
        subject: 'English',
        attendanceRate: 65,
        gpa: 1.8,
        assignmentCompletion: 55,
        behaviorReferrals: 3,
        lateSubmissions: 9,
        notes: 'IEP in place. Needs follow-up with special ed coordinator.',
        tags: ['IEP', 'At-Risk'],
        lastRiskScore: 79,
        lastRiskCategory: 'At Risk',
    },
    {
        id: 'seed-006',
        name: 'Aisha Johnson',
        studentId: 'ST-2024-006',
        grade: '11',
        subject: 'Mathematics',
        attendanceRate: 91,
        gpa: 2.9,
        assignmentCompletion: 78,
        behaviorReferrals: 1,
        lateSubmissions: 4,
        notes: 'GPA dropped from 3.4 last semester. Monitor closely.',
        tags: ['Monitored'],
        lastRiskScore: 41,
        lastRiskCategory: 'Moderate',
    },
    {
        id: 'seed-007',
        name: 'Carlos Rivera',
        studentId: 'ST-2024-007',
        grade: '9',
        subject: 'Science',
        attendanceRate: 79,
        gpa: 2.4,
        assignmentCompletion: 68,
        behaviorReferrals: 1,
        lateSubmissions: 5,
        notes: '',
        tags: [],
        lastRiskScore: 48,
        lastRiskCategory: 'Moderate',
    },
    {
        id: 'seed-008',
        name: 'Lily Chen',
        studentId: 'ST-2024-008',
        grade: '12',
        subject: 'History',
        attendanceRate: 96,
        gpa: 4.0,
        assignmentCompletion: 100,
        behaviorReferrals: 0,
        lateSubmissions: 0,
        notes: 'Class valedictorian candidate.',
        tags: [],
        lastRiskScore: 3,
        lastRiskCategory: 'Low',
    },
    {
        id: 'seed-009',
        name: 'Malik Brown',
        studentId: 'ST-2024-009',
        grade: '10',
        subject: 'English',
        attendanceRate: 48,
        gpa: 1.1,
        assignmentCompletion: 31,
        behaviorReferrals: 6,
        lateSubmissions: 18,
        notes: 'Crisis level. Multiple office referrals. Parents meeting scheduled.',
        tags: ['At-Risk', '504'],
        lastRiskScore: 95,
        lastRiskCategory: 'Critical',
    },
    {
        id: 'seed-010',
        name: 'Emma Rodriguez',
        studentId: 'ST-2024-010',
        grade: '11',
        subject: 'Mathematics',
        attendanceRate: 85,
        gpa: 3.1,
        assignmentCompletion: 87,
        behaviorReferrals: 0,
        lateSubmissions: 2,
        notes: 'Improving trend this semester.',
        tags: [],
        lastRiskScore: 19,
        lastRiskCategory: 'Low',
    },
    {
        id: 'seed-011',
        name: 'Noah Patel',
        studentId: 'ST-2024-011',
        grade: '9',
        subject: 'Science',
        attendanceRate: 76,
        gpa: 2.6,
        assignmentCompletion: 71,
        behaviorReferrals: 1,
        lateSubmissions: 6,
        notes: 'New student, still adjusting.',
        tags: ['ELL'],
        lastRiskScore: 44,
        lastRiskCategory: 'Moderate',
    },
    {
        id: 'seed-012',
        name: 'Grace Kim',
        studentId: 'ST-2024-012',
        grade: '12',
        subject: 'History',
        attendanceRate: 90,
        gpa: 3.5,
        assignmentCompletion: 91,
        behaviorReferrals: 0,
        lateSubmissions: 1,
        notes: 'Excellent participation and class engagement.',
        tags: [],
        lastRiskScore: 12,
        lastRiskCategory: 'Low',
    },
];

export type SeedStudent = typeof SEED_STUDENTS[0];
